version: "1.0"
info:
  model: int-scaffold
packages:
- name: WorkFlows_gitProject
  gitServerName: AnsUmerco
  gitUrl: https://github.com/AnsRizvi-umerco
  gitUsername: AnsRizvi-umerco
  gitBranch: main
